//! Embeds the built frontend into the binary. `frontend/dist` is checked in
//! so a plain `cargo build` needs no Node toolchain; after changing the UI,
//! run `npm run build` in `dashboard/frontend`. When `dist` is missing the
//! build still succeeds and the server serves a page saying how to produce
//! it. Text assets also get a gzip copy, sent to clients that accept one.

use {
    flate2::{Compression, write::GzEncoder},
    std::{env, fs, io::Write, path::Path},
};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dist = Path::new(&manifest_dir).join("frontend").join("dist");
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut entries = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
    }
    entries.sort();

    if entries.is_empty() {
        // Say so during the build. Otherwise the first sign of a missing bundle
        // is the placeholder page, long after the build looked like it worked.
        println!(
            "cargo:warning=agave-dashboard: frontend/dist is empty or missing, so the validator \
             will serve a placeholder page. Run `npm install && npm run build` in \
             dashboard/frontend, then build again."
        );
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_dir = Path::new(&out_dir);
    let mut generated = String::from(
        "// @generated by build.rs from frontend/dist -- do not edit.\n/// Route, content type, \
         file, and its gzip copy.\npub type Asset = (&'static str, &'static str, &'static [u8], \
         Option<&'static [u8]>);\npub static ASSETS: &[Asset] = &[\n",
    );
    for (index, (route, path)) in entries.iter().enumerate() {
        let packed = match gzip_copy(route, path, &out_dir.join(format!("asset-{index}.gz"))) {
            Some(packed) => format!("Some(include_bytes!({packed:?}))"),
            None => "None".to_string(),
        };
        generated.push_str(&format!(
            "    ({route:?}, {:?}, include_bytes!({path:?}), {packed}),\n",
            content_type(route)
        ));
    }
    generated.push_str("];\n");

    fs::write(out_dir.join("assets.rs"), generated).expect("write generated assets");
}

fn collect(root: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    let Ok(read_dir) = fs::read_dir(dir) else {
        return;
    };
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, entries);
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        let route = format!("/{}", relative.to_string_lossy().replace('\\', "/"));
        entries.push((route, path.to_string_lossy().replace('\\', "/")));
    }
}

/// Writes a gzip copy of a text asset to `to` and returns its path, unless it is no smaller.
fn gzip_copy(route: &str, source: &str, to: &Path) -> Option<String> {
    let text = matches!(
        route.rsplit('.').next(),
        Some("html" | "js" | "mjs" | "css" | "json" | "webmanifest" | "svg" | "map")
    );
    if !text {
        return None;
    }
    let raw = fs::read(source).expect("read asset");
    // mtime 0 and no file name, so every build writes the same bytes.
    let mut encoder = GzEncoder::new(Vec::new(), Compression::best());
    encoder.write_all(&raw).expect("gzip asset");
    let packed = encoder.finish().expect("gzip asset");
    if packed.len() >= raw.len() {
        return None;
    }
    fs::write(to, packed).expect("write gzip asset");
    Some(to.to_string_lossy().replace('\\', "/"))
}

fn content_type(route: &str) -> &'static str {
    match route.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("js") | Some("mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("webmanifest") => "application/manifest+json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("webp") => "image/webp",
        Some("ico") => "image/x-icon",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        Some("ttf") => "font/ttf",
        Some("map") => "application/json",
        _ => "application/octet-stream",
    }
}
