//! Embeds the built frontend into the binary.
//!
//! Turning the dashboard on should take one flag and no extra services, so the
//! SPA has to travel inside `agave-validator`. `frontend/dist` is checked in,
//! which lets a plain `cargo build` work without a Node toolchain. After
//! changing the UI, run `npm run build` in `dashboard/frontend` to regenerate
//! it.
//!
//! When `frontend/dist` is missing the build still succeeds, and the server
//! serves a page explaining how to produce it.

use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dist = Path::new(&manifest_dir).join("frontend").join("dist");
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut entries = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
    }
    entries.sort();

    if entries.is_empty() {
        // Say so during the build. Otherwise the first sign of a missing bundle
        // is the placeholder page, long after the build looked like it worked.
        println!(
            "cargo:warning=agave-dashboard: frontend/dist is empty or missing, so the \
             validator will serve a placeholder page. Run `npm install && npm run build` \
             in dashboard/frontend, then build again."
        );
    }

    let mut generated = String::from(
        "// @generated by build.rs from frontend/dist -- do not edit.\n\
         pub static ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );
    for (route, path) in &entries {
        generated.push_str(&format!(
            "    ({route:?}, {:?}, include_bytes!({path:?})),\n",
            content_type(route)
        ));
    }
    generated.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("assets.rs");
    fs::write(&out, generated).expect("write generated assets");
}

fn collect(root: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    let Ok(read_dir) = fs::read_dir(dir) else {
        return;
    };
    for entry in read_dir.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, entries);
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        let route = format!("/{}", relative.to_string_lossy().replace('\\', "/"));
        entries.push((route, path.to_string_lossy().replace('\\', "/")));
    }
}

fn content_type(route: &str) -> &'static str {
    match route.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("js") | Some("mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("webp") => "image/webp",
        Some("ico") => "image/x-icon",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        Some("ttf") => "font/ttf",
        Some("map") => "application/json",
        _ => "application/octet-stream",
    }
}
